### PR TITLE
TypeScript

### PR DESCRIPTION
**Pull request by cpv123**
## Description
- Changed all files to TypeScript, use `tsc` for build
- Export relevant types from `index` along with core functions
- Updated `graphql` and `ra-data-graphql` dependencies (same as https://github.com/hasura/ra-data-hasura/pull/82)
- Removes now-unnecessary `dependencies` and `devDependencies`
- Added some unit tests for helper functions
- Add GH action to run unit tests on PRs into `master`
- Removed unused `buildFragments` function
- Added `prepublishOnly` script

@arjunyel I think this is done. I've tested it locally with an existing project and it seems to be working same as before 🤞

### CODE REVIEW

**Comment by arjunyel** [comment]
Hi friend, thank you so much for doing this!!! Is there anything you need help with?

**Comment by cpursley** [comment]
Thank you so much for this work @cpv123 ~ this has been a dream of ours.

**Comment by arjunyel** [comment]
@cpv123 Thank you so much!!!!!

**Comment by cassus** [comment]
Awesome! Can't wait for this to be released on npm!

**Pull request merged**
