### PR TITLE
Make it possible to filter based on a nested field

### PR DESCRIPTION
**Pull request by remiremi**
With this fix you could have a list filter that filters on a nested object field, for example doing

```tsx

const ProductListFilter = (props: any) => (
  <Filter {...props}>
    <SelectInput
      label="Status"
      source="category.status"
      choices={[
        { id: "in_production", name: "In Production" },
        { id: "planned", name: "Planned" },
        { id: "retired", name: "Retired" }
      ]}
      emptyText="All"
      alwaysOn
    />
  </Filter>
);

export const ProductList = (props: any) => (
  <List
    {...props}
    filters={<ProductListFilter />}
    sort={{ field: "planting_date", order: "ASC" }}
    filterDefaultValues={{ category: { status: "in_production" } }}
  >
    .....
```

### CODE REVIEW

**Comment by pankgeorg** [comment]
Good job@remiremi, though, I think something in this PR seems wrong; the generated query for `category.status@_ilike` is `{category: {"status@_ilike":  {_eq: <value>}}}` and not `{category: {"status": {_ilike:  <value> }}}`

**Comment by pankgeorg** [comment]
I do the same here, following a different path from your approach: https://github.com/hasura/ra-data-hasura/pull/47

**Comment by torquato-nathan** [comment]
Any updates here? I have the same need.

**Comment by praveenweb** [comment]
@remiremi - Thanks for the PR. This looks good. But as @pankgeorg mentioned, the query generation had a minor issue. 

So I have merged #47 and closing this in favour of that.

**Pull request closed without merging**
